require: rubocop-performance

AllCops:
  # note Exclude: overrides, does not merge with, default.
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - '.git/**/*'
    - 'solargraph/*'
    - 'db/schema.rb'

Layout/IndentationConsistency:
  EnforcedStyle: 'rails'

Style/FrozenStringLiteralComment:
  EnforcedStyle: 'when_needed'
  Exclude:
    - 'db/migrate/*'
    - 'config/**/*'
    - 'test/**/*'
    - 'app/mailers/*'
    - 'app/channels/*'
    - 'app/helpers/*'
    - 'app/jobs/*'
    - 'app/channels/*'

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: false

Style/SymbolArray:
  EnforcedStyle: 'brackets'

# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'db/migrate/*'
    - 'app/models/*'
    - 'test/test_helper.rb'
    - 'test/application_system_test_case.rb'
    - 'config/application.rb'
    - 'app/helpers/*'
    - 'app/mailers/*'
